[package]
name = "lfstage"
version = "1.2.0" # package updates, minor improvements, tweaks, dependency updates
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
log = "0.4.22"
log4rs = "1.3.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_derive = "1.0.216"
toml = "0.8.19"
